# UP умеет хранить данные в файле или виртуальной памяти
# файл несколько увеличивает нагрузку, но хранит данные до тех пор, пока его не удалят
# виртуальная память меньше нагружает, но очищается при перезагрузке сервера
# режим гибридности балансирует между ними
# file - файл
# virtual - виртуальная память
# hybrid - гибридность

storage: virtual
# storage: file
# storage: hybrid

# команда для взаимодействия с плагином. требуется право "up.admin"
command: /up

# больше плагинов: https://vk.com/baroness_plugins
# при поддержке devmc.ru