# если выключено, данные будут сбрасываться при каждом рестарте сервера
save_data: true

# НЕ РЕКОМЕНДУЕТСЯ: сохраняет данные только при выключении сервера
# Для крайних случаев, когда требуется пожертвовать функциями ради производительности
save_only_on_disable: false

# право, нужное для команды /up
permission: up.admin

# больше плагинов: https://vk.com/baroness_plugins
# при поддержке devmc.ru